version: "3.9"
services:
  db:
    image: "postgres:14.1"
    environment:
      POSTGRES_USER: ms-user
      POSTGRES_PASSWORD: ms-user-pass
      POSTGRES_DB: ms-user
    ports:
      - 5432:5432
  queue:
    image: "redis:6.2.6"
    ports:
      - 6379:6379
